<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
    }

    protected $username;

    public function getUsername()
    {
        return parent::getUsername(); // TODO: Change the autogenerated stub
    }

    public function setUsername($username)
    {
        return parent::setUsername($username); // TODO: Change the autogenerated stub
    }

}
