<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;


   protected $usernameCanonical;

   public function getUsernameCanonical()
   {
       return parent::getUsernameCanonical(); // TODO: Change the autogenerated stub
   }

   public function setUsernameCanonical($usernameCanonical)
   {
       return parent::setUsernameCanonical($usernameCanonical); // TODO: Change the autogenerated stub
   }

}
