easy_admin:
    formats:
        date: 'd/m/Y'
        time: 'H:i'
        datetime: 'd/m/Y \a H:i:s'
    entities:
        Article:
            class: App\Entity\Article
            label: 'Liste des articles'
            list:
                fields:
                    - id
                    - title
                    - content
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
                    - { property: 'getAuthor', label: 'Created by A :' }
                    - { property: 'updatedAt', format: 'j / M / Y' }
            show:
                fields:
                    - title
                    - content
                    - { property: 'getAuthor', label: 'Created by B :' }
                    - { property: 'updatedAt', format: 'j / M / Y' }
                    - { property: 'image', type: 'image', base_path: '%app.path.article_images%' }
            form:
                fields:
                    - title
                    - content
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }
                    - { type: 'divider' }
                    - author
                    - { property: 'updatedAt' }
                    - { type: 'divider' }